services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: bankos
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankos
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: